package workloads

var STATES = [][]string{
	[]string{"AK", "Alaska"},
	[]string{"AL", "Alabama"},
	[]string{"AR", "Arkansas"},
	[]string{"AS", "American Samoa"},
	[]string{"AZ", "Arizona"},
	[]string{"CA", "California"},
	[]string{"CO", "Colorado"},
	[]string{"CT", "Connecticut"},
	[]string{"DC", "District of Columbia"},
	[]string{"DE", "Delaware"},
	[]string{"FL", "Florida"},
	[]string{"GA", "Georgia"},
	[]string{"GU", "Guam"},
	[]string{"HI", "Hawaii"},
	[]string{"IA", "Iowa"},
	[]string{"ID", "Idaho"},
	[]string{"IL", "Illinois"},
	[]string{"IN", "Indiana"},
	[]string{"KS", "Kansas"},
	[]string{"KY", "Kentucky"},
	[]string{"LA", "Louisiana"},
	[]string{"MA", "Massachusetts"},
	[]string{"MD", "Maryland"},
	[]string{"ME", "Maine"},
	[]string{"MI", "Michigan"},
	[]string{"MN", "Minnesota"},
	[]string{"MO", "Missouri"},
	[]string{"MP", "Northern Mariana Islands"},
	[]string{"MS", "Mississippi"},
	[]string{"MT", "Montana"},
	[]string{"NA", "National"},
	[]string{"NC", "North Carolina"},
	[]string{"ND", "North Dakota"},
	[]string{"NE", "Nebraska"},
	[]string{"NH", "New Hampshire"},
	[]string{"NJ", "New Jersey"},
	[]string{"NM", "New Mexico"},
	[]string{"NV", "Nevada"},
	[]string{"NY", "New York"},
	[]string{"OH", "Ohio"},
	[]string{"OK", "Oklahoma"},
	[]string{"OR", "Oregon"},
	[]string{"PA", "Pennsylvania"},
	[]string{"PR", "Puerto Rico"},
	[]string{"RI", "Rhode Island"},
	[]string{"SC", "South Carolina"},
	[]string{"SD", "South Dakota"},
	[]string{"TN", "Tennessee"},
	[]string{"TX", "Texas"},
	[]string{"UT", "Utah"},
	[]string{"VA", "Virginia"},
	[]string{"VI", "Virgin Islands"},
	[]string{"VT", "Vermont"},
	[]string{"WA", "Washington"},
	[]string{"WI", "Wisconsin"},
	[]string{"WV", "West Virginia"},
	[]string{"WY", "Wyoming"},
}

var NUM_STATES = len(STATES)
